2.1

diff --git a/run b/run
--- a/run
+++ b/run
@@ -88,11 +88,18 @@ case "$CMD" in
         ( cd $MYDIR/dockerwebpart; sudo docker build -t $WEB_IMAGE . )
         ;;
    initdb)
-        echo -n "Init DB ... "
+        VER=$(sudo docker exec -t $DB_CONTAINER mongod --version | head -1)
+        echo "Mongo $VER"
         # Mongo command (ver 4.0: mongo ; ver 5.0+: mongosh)
         MONGO=mongo
         RET=$(sudo docker exec -t $DB_CONTAINER which $MONGO)
         [ -z "$RET" ] && MONGO=mongosh
+        RET=$(sudo docker exec -t $DB_CONTAINER cat /proc/cpuinfo | grep avx 1>/dev/null 2>/dev/null; echo $?)
+        if [ $MONGO == "mongosh" -a $RET -ne 0 ]; then
+            echo "ERROR: AVX support is disabled - See https://inrae.github.io/pgd-mmdt/avx_win11_vbox/"
+            exit 1
+        fi
+        echo -n "Init DB ... "
         sudo docker exec -t $DB_CONTAINER /bin/bash -c "cd /js; python3 ./generate_setupdb.py"
         sudo docker exec -t $DB_CONTAINER $MONGO /js/setupdb.js 1>/dev/null 2>/dev/null
         [ $? -eq 0 ] && echo OK
@@ -117,7 +124,9 @@ case "$CMD" in
         sudo docker volume rm $MONGO_VOL
         ;;
    delimages)
-        sudo docker rmi -f $(sudo docker images | grep pgd-mmdt- | sed -e "s/  \+/@/g" | cut -d'@' -f3)
+        sudo docker rmi -f $(sudo docker images | grep $WEB_IMAGE | sed -e "s/  \+/@/g" | cut -d'@' -f3)
+        sudo docker rmi -f $(sudo docker images | grep $SCAN_IMAGE | sed -e "s/  \+/@/g" | cut -d'@' -f3)
+        sudo docker rmi -f $(sudo docker images | grep $DB_IMAGE | sed -e "s/  \+/@/g" | cut -d'@' -f3)
         ;;
    *) usage
       exit 2
