2.1

diff --git a/run b/run
--- a/run
+++ b/run
@@ -52,6 +52,7 @@ case "$CMD" in
         # Check / Create some directories (cache, tmp) with full privileges
         [ ! -d $MYDIR/web/tmp ] && sudo mkdir -p $MYDIR/web/tmp
         [ -d $MYDIR/web/tmp ] && sudo chmod 777 $MYDIR/web/tmp
+        [ -d $MYDIR/web/tmp ] && sudo rm -f $MYDIR/web/tmp/*
         [ ! -d $MYDIR/web/cache ] && sudo mkdir -p $MYDIR/web/cache
         [ -d $MYDIR/web/cache ] && sudo chmod 777 $MYDIR/web/cache
         # Set full privileges to json configuration files
@@ -120,6 +121,10 @@ case "$CMD" in
             echo "ERROR: AVX support is disabled - See https://inrae.github.io/pgd-mmdt/avx_win11_vbox/"
             exit 1
         fi
+        # echo -n "Convert config. files from TSV to JSON ..."
+        # sudo docker exec -i $WEB_CONTAINER php ./convert
+        # [ $? -eq 0 ] && echo OK
+        # [ $? -ne 0 ] && echo FAILED
         echo -n "Init DB ... "
         sudo docker exec -t $DB_CONTAINER /bin/bash -c "cd /js; python3 ./generate_setupdb.py"
         sudo docker exec -t $DB_CONTAINER $MONGO /js/setupdb.js 1>/dev/null 2>/dev/null
